name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Build React App
        run: |
          cd apps/hello-react
          npm install
          npm run build
          cd ../../
          ls

      - name: Deploy React App
        run: wrangler pages publish apps/hello-react/dist --project-name test-mono-react --branch main
        env:
          CLOUDFLARE_API_TOKEN: LERcWduzQns_35a4MSJGCEsVydioCOYka936q_2r

      - name: Deploy Static Page
        run: wrangler pages publish apps/static-page --project-name=test-mono --branch main
        env:
          CLOUDFLARE_API_TOKEN: LERcWduzQns_35a4MSJGCEsVydioCOYka936q_2r 

