name: Another workflow

on:
  workflow_dispatch: 
  push:               
    branches: [ test-workflow ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"